In [2]:
import numpy as np

a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [5]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print("Vectorized version: " + str(1000*(toc-tic))+ "ms")

Vectorized version: 0.4107952117919922ms


In [3]:
import numpy as np
import time

# 큰 배열 생성
size = 10**7  # 1천만 개의 원소를 가진 배열
a = np.random.rand(size)
b = np.random.rand(size)

# 벡터화된 버전 (NumPy의 빠른 연산 활용)
tic = time.time()
c = np.dot(a, b)  # 벡터 내적
toc = time.time()

print("Vectorized version: " + str(1000*(toc - tic)) + " ms")

# 루프를 사용한 버전 (속도가 느림)
tic = time.time()
c = 0
for i in range(size):
    c += a[i] * b[i]  # 루프를 이용한 내적 계산
toc = time.time()

print("Loop version: " + str(1000*(toc - tic)) + " ms")

Vectorized version: 2.3345947265625 ms
Loop version: 1643.9697742462158 ms


In [4]:
import torch
import time

# GPU가 사용 가능한지 확인
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# 큰 배열 생성
a = torch.randn(1000000, device=device)
b = torch.randn(1000000, device=device)

# 벡터화된 연산
tic = time.time()
c = torch.dot(a, b)
toc = time.time()
print(f"Vectorized version: {1000 * (toc - tic)} ms")

Using device: cuda
Vectorized version: 108.3369255065918 ms


In [ ]:
# 1. 선형 결합: z = w^T * x + b
'z는 선형 결합에 대한 결과값\
    x는 입력 특성 벡터 == 입력 데이터\
        wT는 가중치 벡터 w의 전치 행렬\
            b는 편향으로 선형결합에 더해지는 상수'

# 입력 데이터(x)와 가중치 벡터w를 이용해 결과값 z를 계산하는 단계

# 2. 시그모이드 함수: a = sigmoid(z)
'a는 시그모이드 함수로 z를 0과 1사이의 확률 값으로 변환한다.'

In [6]:
import numpy as np
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])
A

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [15]:
cal = A.sum(axis=0)
print(cal)

percentage = 100*A/cal.reshape(1, 4)
print(percentage)

[ 59.  239.  155.4  76.9]
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [13]:
# axis=0: 열 단위로 더함, axis=1: 행 단위로 더함, 기본값은 None: 배열의 모든 요소를 더한다.
# reshape: 배열의 차원을 변경하는 함수 

0.028314028314028315

In [ ]:
import numpy as np

a = np.random.randn(10000)  # 10000개의 난수 생성
mean_a = np.mean(a)
std_a = np.std(a)

print("평균:", mean_a)
print("표준 편차:", std_a)

In [15]:
import numpy as np

a = np.random.randn(5)
# 표준 정규 분포에서 무작위로 샘플을 생성한다. 표준 정규 분포는 평균이 0이고, 표준 편차가 1인 분포(가우시안 분포)
a

array([-1.66556704,  0.30844055, -0.92700111,  0.14808966, -0.77674165])

In [17]:
print(a.T)
a.T.shape

# 1차원 벡터는 전치를 해도 변화하지 않는다.

A = np.random.randn(5, 1) # 2차원 배열로 만든다.

[-1.66556704  0.30844055 -0.92700111  0.14808966 -0.77674165]


(5,)

# 뉴런
1. 입력 (x): 여러값들이 뉴런으로 들어온다. 이 입력값들은 특징 벡터로 생각할 수 있다
2. 가중치 (W): 뉴런은 각 입력값에 대해 가중치를 부여한다. 
3. 편향 (b): 가중치와 입력의 곱에 더해지는 상수, 편향은 뉴런의 출력을 조정하는 데 사용된다
4. 선형 결합(z= W*x +b): 입력과 가중치를 곱한 후 편향을 더하는 단계, 선형함수
5. 활성화 함수(g(z)): 선형결합으로 계산된 값을 비선형적으로 변환하는 함수, 활성화 함수는 모델에 비선형성을 추가하며, ReLU, 시그모이드, Tanh등의 함수가 자주 사용된다
6. 출력: 뉴런의 최종 출력은 활성화 함수를 통과한 값으로 다음층의 뉴런에게 전달되거나 모델의 최종 출력으로 사용된다.

In [19]:
x=np.array([[[1],[2]],[[3],[4]]])
x.shape

(2, 2, 1)

In [20]:
a=np.array([[1,2], [3,4]])
a.shape

(2, 2)

In [22]:
a=np.random.randn(3,4) 
b=np.random.randn(1,4)
c = a+b
c.shape

(3, 4)

In [26]:
a=np.random.randn(4,3)
b=np.random.randn(3,2) 
c= a*b
c.shape

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [28]:
a=np.array([[2,1],[1,3]])
b = a*a
b

array([[4, 1],
       [1, 9]])

In [ ]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [32]:
a = np.array([[[1,2,3]],  [[5, 6], [7, 8]]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.