In [3]:
import torch
import tensorflow as tf
import numpy as np

# 벡터는 1차원 배열로, 크기와 방향을 가진 수학적 객체

# 텍서는 벡터를 더 일반화한 개념, 다차원 배열을 의미한다. 텐서는 0차원인 스칼라 부터 시작하여, 1차원인 벡터, 2차원인 행렬, 그리고 그 이상의 차원을 가지는 객체를 포함하는 개념

# L1 노름: 벡터의 모든 성분의 절대값을 더한 값. 특정 성분만 중요한 경우 L1노름은 작은 값을 0으로 만드는 성향이 있기 때문에
# 희소한 벡터를 찾을 때 자주 사용된다.

# L2 노름: 모든 성분을 균등하게 처리하며, 부드럽고 균형 잡힌 최적화를 목표로 할 때 사용된다.

# 프로테비우스 노름: 행렬의 각 원소의 제곱을 더한 후, 그 값에 제곱근을 취한 값. 행렬의 크기나 에러를 측정할 때 사용된다. 행렬을 다룰 때 L2노름과 아주 유사하다.

In [4]:
# 넘파이 노름 계산

In [5]:
# L1 노름 (벡터의 모든 성분의 절대값을 더한 값) / 양수, 음수 구분하지 않는다.
x = np. array([1, -2, 3])

l1_norm = np.linalg.norm(x, ord=1)
print("l1 norm: ", l1_norm)

l1 norm:  6.0


In [6]:
# L2 노름 (벡터의 각 성분의 제곱을 합한 후 제곱근을 취한 값)
l2_norm = np.linalg.norm(x, ord=2)
print("l2 norm: ", l2_norm)

l2 norm:  3.7416573867739413


In [7]:
# 프로테비이우스 노름 (벡터의 각 성분의 제곱을 합한 후 제곱근을 취한 값)
A = np.array([[1, 2], [3, 4]])
fro_norm = np.linalg.norm(A, ord='fro')
print("Frobenius norm: ", fro_norm)

Frobenius norm:  5.477225575051661


In [8]:
x = np.array([[1, 2], [3, 4]])
(1**2 + 2 **2 + 3 **2 + 4 **2) ** (1/2)

5.477225575051661

In [9]:
# 파이토치 노름 / 넘파이는 정수로도 실행되지만 파이토치와 텐서플로는 실수로만 실행된다.
x_pt = torch.tensor([[1, -2], [3, 4.]])
print(torch.norm(x_pt, p=1))
print(torch.norm(x_pt, p=2))
print(torch.norm(x_pt, p='fro'))

tensor(10.)
tensor(5.4772)
tensor(5.4772)


In [10]:
# 텐서플로 노름
x = tf.constant([1.0, -2.0, 3.0])

# L1 노름 계산
l1_norm = tf.norm(x, ord=1)
print("L1 노름:", l1_norm.numpy())

# L2 노름 계산
l2_norm = tf.norm(x, ord=2)
print("L2 노름:", l2_norm.numpy()) 

A = tf.constant([[1.0, 2.0], [3.0, 4.0]])

# 프로테비우스 노름 계산 (ord 생략)
fro_norm = tf.norm(A)
print("프로테비우스 노름:", fro_norm.numpy())

L1 노름: 6.0
L2 노름: 3.7416575
프로테비우스 노름: 5.477226


# 행렬에 대한 노름의 정의
행렬에도 L1, L2 노름을 적용할 수 있지만, 그 의미가 벡터와는 다르게 정의됩니다.

행렬에 대한 L1 노름: 행의 절댓값의 합 중 최대값을 의미합니다. 즉, 각 열에서 절댓값의 합을 계산한 후, 그 중에서 가장 큰 값을 반환합니다.
행렬에 대한 L2 노름: 행렬의 가장 큰 특이값으로 정의됩니다. 즉, 행렬의 변환이 가장 많이 발생하는 크기를 나타냅니다. 벡터에서의 L2 노름이 유클리드 거리라면, 행렬에서의 L2 노름은 변환의 최대 크기입니다.

이와 달리, 프로테비우스 노름은 벡터의 L2 노름을 행렬로 확장한 것

# np.dot() 함수는 **내적(dot product)**과 행렬 곱셈(matrix multiplication) 모두에 사용

# 내적: 벡터 간의 내적은 두 벡터의 대응하는 원소끼리 곱한 값을 모두 더한 값
np.dot(v, w)**는 두 벡터의 내적을 계산

# 행렬 곱셈은 벡터의 내적을 확장한 개념, 행렬의 행과 다른 행렬의 열의 내적을 이용하여 새로운 행렬을 만드는 방식
np.dot(A, B)**는 행렬 곱셈을 수행합니다. 만약 A,B가 행렬이라면 행렬 곱셉이 이루어진다.

# 내적은 1차원 벡터 간의 연산을 의미하고, 행렬 곱셈은 2차원 이상의 행렬에서 행과 열의 내적을 계산하는 방식

In [11]:
# 행렬 곱셈, 넘파이
A = np.array([[3, 4], [5, 6], [7, 8]])
b = np.array([[1], [2]])
A, b

np.dot(A, b)

array([[11],
       [17],
       [23]])

In [12]:
# 행렬 곱셈, 파이토치
A_pt = torch.tensor([[3, 4], [5, 6], [7, 8]])
b_pt = torch.tensor([[1], [2]])

torch.matmul(A_pt, b_pt)

tensor([[11],
        [17],
        [23]])

In [13]:
# 행렬 곱셈, 텐서플로
A_tf = tf.Variable([[3, 4], [5, 6], [7, 8]])
b_tf = tf.constant([[1, 2]])

tf.linalg.matvec(A_tf, b_tf)

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[11, 17, 23]])>

In [14]:
b = np.array([[1, 9], [2, 0]])
A, b

(array([[3, 4],
        [5, 6],
        [7, 8]]),
 array([[1, 9],
        [2, 0]]))

In [15]:
# 넘파이 배열을 파이토치, 텐서플로 텐서로 변환
A = np.array([[3, 4], [5, 6], [7, 8]])
B = np.array([[1, 9], [2, 0]])
A,B 

(array([[3, 4],
        [5, 6],
        [7, 8]]),
 array([[1, 9],
        [2, 0]]))

In [16]:
# 넘파이
np.dot(A, B)

array([[11, 27],
       [17, 45],
       [23, 63]])

In [17]:
# 파이토치
A_pt = torch.from_numpy(A)
B_pt = torch.from_numpy(B)
A_pt, B_pt

(tensor([[3, 4],
         [5, 6],
         [7, 8]], dtype=torch.int32),
 tensor([[1, 9],
         [2, 0]], dtype=torch.int32))

In [18]:
torch.matmul(A_pt, B_pt)

tensor([[11, 27],
        [17, 45],
        [23, 63]], dtype=torch.int32)

In [19]:
# 텐서플로
A_tf = tf.Variable(A) # 변경 가능한
B_tf = tf.Variable(B)

A_tf2 = tf.convert_to_tensor(A, dtype=tf.float32) # 변경 불가능한
A_tf, A_tf2

(<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
 array([[3, 4],
        [5, 6],
        [7, 8]])>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[3., 4.],
        [5., 6.],
        [7., 8.]], dtype=float32)>)

In [20]:
tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 27],
       [17, 45],
       [23, 63]])>

# tf.linalg.matvec: 행렬과 벡터의 곱셈
행렬과 벡터 간의 곱셉을 수행한다.
출력 결과는 벡터

# tf.linalg.matmul: 행렬과 행렬 간의 곱셉
두개의 행렬을 입력으로 받는다. 결과는 행렬

In [21]:
# 대칭 행렬
# 전치해도 행렬이 그대로 유지된다
x_sym = np.array([[0, 1, 2], [1, 7, 8], [2, 8, 9]])  
x_sym

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [22]:
x_sym.T

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [23]:
x_sym == x_sym.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [28]:
# 파이 토치
I = torch.Tensor([[0, 1, 2], [1, 7, 8], [2, 8, 9]])
I_pt = I.t()
I_pt, I

(tensor([[0., 1., 2.],
         [1., 7., 8.],
         [2., 8., 9.]]),
 tensor([[0., 1., 2.],
         [1., 7., 8.],
         [2., 8., 9.]]))

In [27]:
I_pt = I.t()
I_pt

tensor([[0., 1., 2.],
        [1., 7., 8.],
        [2., 8., 9.]])

In [ ]:
# 단위 행렬: 대각 성분이 1이고 나머지 성분이 0인 정방 행렬

In [30]:
# 넘파이
I_3 = np.eye(3)
I_5 = np.eye(5)
I_3, I_5

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]))

In [44]:
np.dot(I_3, I_3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
# 파이토치
I_3_pt = torch.eye(3, dtype=torch.long) # float32 타입 / 단위형을 정수로 변환
x_pt = torch.tensor([25, 2, 5]) # int64 타입
# , dtype=torch.float32 / float32 타입으로 변환
torch.matmul(I_3_pt, x_pt)

tensor([25,  2,  5])

In [43]:
# 2차원 배열로 y를 세로로 정의
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
y = np.array([[-1], [1], [-2]])  # 2차원 세로 벡터로 정의

# 행렬 곱셈
result = np.dot(x, y)
print(result)


[[ -3]
 [ -9]
 [-15]]


In [45]:
# 파이토치 행렬 곱셈
x_pt = torch.Tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
y_pt = torch.Tensor([[-1, 0], [1, 1], [-2, 2]])
x_pt, y_pt

(tensor([[0., 1., 2.],
         [3., 4., 5.],
         [6., 7., 8.]]),
 tensor([[-1.,  0.],
         [ 1.,  1.],
         [-2.,  2.]]))

In [46]:
torch.matmul(x_pt, y_pt)

tensor([[ -3.,   5.],
        [ -9.,  14.],
        [-15.,  23.]])

In [47]:
# 텐서플로 행렬 곱셈
x_tf = tf.Variable([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
y_tf = tf.Variable([[-1, 0], [1, 1], [-2, 2]])

tf.matmul(x_tf, y_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ -3,   5],
       [ -9,  14],
       [-15,  23]])>

In [ ]:
# tf.linalg.matvec(x_tf, y_tf) / 벡터와 행렬의 곱셈은 matvec 함수를 사용한다.

In [49]:
# 역행렬: 정사각 행렬 A에 대해 AB = BA = I를 만족하는 행렬 B를 A의 역행렬이라고 한다. 행렬식이 0이 아니어야 한다.
A = np.array([[1, 2], [3, 4]])

# 역행렬 계산 det(A)=ad−bc
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [50]:
# 파이토치 역행렬
A = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

A_inv = torch.inverse(A)
print(A_inv)

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])


In [51]:
# 텐서플로 역행렬
A = tf.constant([[1.0, 2.0], [3.0, 4.0]])

A_inv = tf.linalg.inv(A)
print(A_inv)

tf.Tensor(
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]], shape=(2, 2), dtype=float32)


In [ ]:
# 대각행렬: 대각선 요소를 제외한 나머지 모든 요소가 0인 정사각행렬
# 곱셈과 덧셈에서 연산이 단순해진다. 

In [1]:
# 역행렬 추가 ad−bc
# 행렬 A와 역행렬 A_inv의 곱셈은 항상 단위행렬 I가 된다.

import numpy as np

# A 배열 정의 (임의의 2x2 정사각 행렬)
A = np.array([[4, 7],
              [2, 6]])

# A의 역행렬로 B 계산
B = np.linalg.inv(A)

# 단위 행렬 I
I = np.eye(2) # 모든 대각선 요소가 1이고, 나머지는 모두 0인 행렬

# A * B와 B * A를 계산하여 단위 행렬과 비교
AB = np.dot(A, B)
BA = np.dot(B, A)

print("A 배열:\n", A)
print("\nB 배열 (A의 역행렬):\n", B)
print("\nA * B:\n", AB)
print("\nB * A:\n", BA)
print("\nA * B와 단위 행렬 I가 같은가?", np.allclose(AB, I)) # 두 배열이 작은 오차 내에서 거의 같은지 확인
print("\nB * A와 단위 행렬 I가 같은가?", np.allclose(BA, I))

A 배열:
 [[4 7]
 [2 6]]

B 배열 (A의 역행렬):
 [[ 0.6 -0.7]
 [-0.2  0.4]]

A * B:
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]

B * A:
 [[1.00000000e+00 6.66133815e-16]
 [0.00000000e+00 1.00000000e+00]]

A * B와 단위 행렬 I가 같은가? True

B * A와 단위 행렬 I가 같은가? True


# 넘파이
A_inv = np.linalg.inv(A)

# 파이토치
A_inv = torch.inverse(A)

# 텐서플로
A_inv = tf.linalg.inv(A)

In [ ]:
# 대각 행렬: 연산이 간단하고 효율적인 특징, 대각선 이외이 모든 요소가 0인 정사각 행렬

In [5]:
import numpy as np
import tensorflow as tf
import torch

# 넘파이 대각행렬
D = np.diag([1, 2, 3, 4])

# 파이토치 대각행렬
D_pt = torch.diag(torch.tensor([1, 2, 3, 4]))

# 텐서플로 대각행렬
D_tf = tf.linalg.diag([1, 2, 3, 4])

print("Numpy Diagonal Matrix:\n", D)
print("\nPyTorch Diagonal Matrix:\n", D_pt)
print("\nTensorFlow Diagonal Matrix:\n", D_tf)

Numpy Diagonal Matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

PyTorch Diagonal Matrix:
 tensor([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]])

TensorFlow Diagonal Matrix:
 tf.Tensor(
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]], shape=(4, 4), dtype=int32)


In [14]:
# 직교 행렬: 행 벡터들과 열 벡터들이 서로 직교인 정사각행렬
# 전치 행렬이 곧 역행렬

# 단위 행렬은 직교 행렬의 한 예입니다.
Q = np.eye(3)  # 3x3 단위 행렬
print("Numpy 직교 행렬:\n", Q)

# 임의의 직교 행렬을 생성 (QR 분해 사용)
A = np.random.rand(3, 3)
Q, R = np.linalg.qr(A)
print("임의의 3x3 직교 행렬 (QR 분해 사용):\n", Q)

Numpy 직교 행렬:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
임의의 3x3 직교 행렬 (QR 분해 사용):
 [[-0.35727565  0.93012852  0.08494137]
 [-0.71566772 -0.2141883  -0.664788  ]
 [-0.60014483 -0.29830236  0.74218723]]


In [ ]:
# 파이토치 직교 행렬
# 단위 행렬 (직교 행렬)
Q = torch.eye(3)  # 3x3 단위 행렬
print("PyTorch 직교 행렬:\n", Q)

# QR 분해를 사용하여 직교 행렬 생성
A = torch.rand(3, 3)
Q, R = torch.qr(A)
print("임의의 3x3 직교 행렬 (QR 분해 사용):\n", Q)

In [ ]:
# 텐서플로 직교 행렬
# 단위 행렬 (직교 행렬)
Q = tf.eye(3)  # 3x3 단위 행렬
print("TensorFlow 직교 행렬:\n", Q)

# QR 분해를 사용하여 직교 행렬 생성
A = tf.random.normal((3, 3))
Q, R = tf.linalg.qr(A)
print("임의의 3x3 직교 행렬 (QR 분해 사용):\n", Q)

# 넘파이 직교행렬
Q, R = np.linalg.qr(A)

# 파이토치 직교행렬
Q, R = torch.qr(A)

# 텐서플로 직교행렬
Q, R = tf.linalg.qr(A)

In [ ]:
'두 벡터의 내적이 0이면 두 벡터는 직교한다'

In [16]:
# 연습문제 1: 종이와 펜을 사용하여 𝐼3 의 두 열을 내적(dots product)하여, 두 열이 서로 직교함을 증명하시오.
i3 = np.eye(3)
i3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 3x3 단위 행렬
i3 = np.eye(3)

# i3의 전치 행렬과 i3를 곱해서 내적을 한 번에 계산
dot_matrix = np.dot(i3.T, i3)

print("각 열 벡터 간의 내적 행렬:")
print(dot_matrix)

In [ ]:
import numpy as np

# 3x3 단위 행렬
i3 = np.eye(3)

# 열 벡터 간 내적 계산
dot_1_2 = np.dot(i3[:, 0], i3[:, 1])  # 첫 번째 열과 두 번째 열
dot_1_3 = np.dot(i3[:, 0], i3[:, 2])  # 첫 번째 열과 세 번째 열
dot_2_3 = np.dot(i3[:, 1], i3[:, 2])  # 두 번째 열과 세 번째 열

print(f"첫 번째 열과 두 번째 열의 내적: {dot_1_2}")
print(f"첫 번째 열과 세 번째 열의 내적: {dot_1_3}")
print(f"두 번째 열과 세 번째 열의 내적: {dot_2_3}")

In [2]:
import numpy as np
import torch
import tensorflow as tf

In [4]:
# 이번에는 행렬 K를 사용하여 연습문제 1번에서 3번까지를 다시 수행하여, 𝐾 직교 행렬인지 평가하시오.
K = np.array([[2/3, 1/3, 2/3], [-2/3, 2/3, 1/3], [1/3, 2/3, -2/3]])
K

array([[ 0.66666667,  0.33333333,  0.66666667],
       [-0.66666667,  0.66666667,  0.33333333],
       [ 0.33333333,  0.66666667, -0.66666667]])

# 벡터 정의
a = [a1, a2, a3]
b = [b1, b2, b3]

# 내적 수식 계산
dot_product = a[0] * b[0] + a[1] * b[1] + a[2] * b[2]

In [ ]:
# 넘파이 내적 계산
K_dot = np.dot(K.T, K)

In [ ]:
# 파이토치 내적 계산
'1차원 벡터 내적'
a = torch.tensor([a1, a2, a3])
b = torch.tensor([b1, b2, b3])
K_pt = torch.dot(a, b)

'2차원 이상의 행렬 곱셈'
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])
result = torch.matmul(A, B)

In [ ]:
# 텐서플로 내적 계산
'1차원 벡터 내적'
a = tf.constant([a1, a2, a3])
b = tf.constant([b1, b2, b3])
dot_product = tf.tensordot(a, b, axes=1)

'2차원 행결 곱셈 (matmul 함수 사용)'
result = tf.matmul(A, B)

넘파이: np.dot(a, b)
파이토치: torch.dot(a, b) (1차원 벡터), torch.matmul(A, B) (행렬 곱)
텐서플로: tf.tensordot(a, b, axes=1) (1차원 벡터), tf.matmul(A, B) (행렬 곱)